name: Build Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Construire l'image Docker
        run: docker build -t mon-app .

      - name: Vérifier que l'image existe
        run: docker images
